# Generated by Django 3.1.7 on 2021-03-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('surname2', models.CharField(blank=True, max_length=100)),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('alias', models.BooleanField()),
            ],
            options={
                'db_table': 'persons',
                'managed': True,
            },
        ),
    ]
