# Generated by Django 3.2 on 2021-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='retypes',
            field=models.IntegerField(choices=[(0, 'Wife'), (1, 'Husband'), (2, 'Son'), (3, 'Daughter'), (4, 'Father'), (5, 'Mother'), (6, 'Grandfather'), (7, 'Grandmother'), (8, 'Grandson'), (9, 'Granddaughter'), (10, 'Friend'), (11, 'Boss'), (12, 'Subordinate'), (13, 'Cousin'), (14, 'Brother'), (15, 'Sister'), (16, 'Couple'), (17, 'Mother in law'), (18, 'Father in law'), (19, 'Daughter in law'), (20, 'Son in law')]),
        ),
    ]
