# Generated by Django 3.1.7 on 2021-04-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vipcontacts.person'),
        ),
        migrations.AlterField(
            model_name='personrelation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personrelation', to='vipcontacts.person'),
        ),
    ]
