# Generated by Django 3.2 on 2021-04-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0002_alter_relationship_retypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
