# Generated by Django 3.1.7 on 2021-04-09 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0002_auto_20210408_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dt_obsolete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dt_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
