# Generated by Django 3.1.7 on 2021-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0002_remove_person_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField()),
                ('dt_obsolete', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=10, null=True)),
                ('city', models.CharField(max_length=100)),
                ('countrys', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'adresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField()),
                ('model', models.CharField(max_length=30)),
                ('before', models.CharField(max_length=1000)),
                ('after', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField()),
                ('dt_obsolete', models.DateTimeField(null=True)),
                ('type', models.IntegerField(choices=[(0, 'Wife'), (1, 'Husband'), (2, 'Son'), (3, 'Daughter')])),
            ],
            options={
                'db_table': 'personsrelations',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Man'), (1, 'Woman')]),
        ),
    ]
