# Generated by Django 3.1.7 on 2021-04-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0003_auto_20210402_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vipcontacts.person'),
        ),
    ]
