# Generated by Django 3.2 on 2021-04-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0003_alter_address_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='chips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
