# Generated by Django 3.1.7 on 2021-04-09 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0003_auto_20210409_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_obsolete', models.DateTimeField(null=True)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('profession', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('department', models.CharField(blank=True, max_length=300)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='vipcontacts.person')),
            ],
            options={
                'db_table': 'jobs',
                'managed': True,
            },
        ),
    ]
