# Generated by Django 3.1.7 on 2021-04-10 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0004_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_obsolete', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='vipcontacts.person')),
            ],
            options={
                'db_table': 'groups',
                'managed': True,
            },
        ),
    ]
