# Generated by Django 3.1.7 on 2021-04-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0004_auto_20210402_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='dt_update',
            new_name='datetime',
        ),
    ]
