# Generated by Django 3.1.7 on 2021-04-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0005_auto_20210402_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vipcontacts.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destiny', to='vipcontacts.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='vipcontacts.person'),
        ),
    ]
