# Generated by Django 3.1.7 on 2021-04-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0006_auto_20210402_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationShip',
        ),
    ]
