# Generated by Django 3.2 on 2021-04-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0006_alter_relationship_retypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.BinaryField()),
                ('mime', models.CharField(choices=[('image/png', 'Png'), ('image/jpeg', 'Jpeg')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('photocontact', models.BooleanField(default=False, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob', to='vipcontacts.person')),
            ],
            options={
                'db_table': 'blobs',
                'managed': True,
            },
        ),
    ]
