# Generated by Django 3.2 on 2021-04-27 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0007_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='dt_obsolete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blob',
            name='dt_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
