# Generated by Django 3.1.7 on 2021-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0008_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='type',
            new_name='retypes',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='type',
            new_name='retypes',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='type',
            new_name='retypes',
        ),
    ]
