# Generated by Django 3.1.7 on 2021-04-02 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0009_auto_20210402_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vipcontacts.person'),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('dt_obsolete', models.DateTimeField(null=True)),
                ('retypes', models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (2, 'Other')])),
                ('phone', models.CharField(max_length=10, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='vipcontacts.person')),
            ],
            options={
                'db_table': 'phones',
                'managed': True,
            },
        ),
    ]
