# Generated by Django 4.0.4 on 2022-04-29 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0009_alter_blob_mime_alter_log_person_alter_phone_retypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='vipcontacts.person'),
        ),
    ]
