# Generated by Django 3.1.7 on 2021-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0011_auto_20210402_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='retypes',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Work'), (2, 'Other')]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='retypes',
            field=models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (3, 'Home mobile'), (4, 'Personal mobile'), (5, 'Others')]),
        ),
    ]
