# Generated by Django 3.1.7 on 2021-04-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0012_auto_20210402_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='vipcontacts.person'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='retypes',
            field=models.IntegerField(choices=[(0, 'Home'), (1, 'Work'), (3, 'Personal mobile'), (4, 'Work mobile'), (5, 'Others')]),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship', to='vipcontacts.person'),
        ),
    ]
