# Generated by Django 3.1.7 on 2021-04-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vipcontacts', '0013_auto_20210403_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vipcontacts.person')),
                ('string', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'searchs',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='retypes',
            field=models.IntegerField(choices=[(0, 'Contact value changed'), (1, 'Contact value added'), (100, 'Personal')]),
        ),
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
    ]
